version: '3.1'

services:
  basic-db:
    build: './db'
    container_name: sir-basic-db1
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "./db/backup:/backup"
    ports:
      - "33060:3306"

  basic-web:
    build: './web'
    container_name: sir-basic-web1
    restart: always
    volumes:
      - "./web/backup:/backup"
      - "./web/html:/var/www/html/sir1"
    depends_on:
      - basic-db
    ports:
      - "8000:80"
